import pyinstaller_versionfile

pyinstaller_versionfile.create_versionfile(
    output_file="version.ini",
    version="1.0.0.0",
    company_name="Octoprint_NVF",
    file_description="A post-processor for the gcode generated by the slicer to add spool data easily.",
    internal_name="NVF Postprocessor",
    legal_copyright="© Octoprint_NVF. All rights reserved.",
    original_filename="nvfPostprocessor.exe",
    product_name="NVF Post-processor",
)