name: Bug report
description: Create a report to help us improve
title: "[BUG] Your bug"
labels: [bug]

body:
  - type: markdown
    attributes:
      value: >-
        **Thank you for wanting to report a bug in Nozzle-Filament-Post-Processor!**

          * First, be sure you are running the [latest version of the Nozzle-Filament--Post-Processor](https://github.com/Rylan-Meilutis/Nozzle-Filament-Post-Processor/releases).
        
        * If Possible please include the following :
        **Describe the bug**
        A clear and concise description of what the bug is.
        
        **To Reproduce**
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
        
        Thank you for your help!
  - type: textarea
    attributes:
      label: The problem
      description: >-
        Describe the issue you are experiencing here. Tell us what you were trying to do
        step by step, and what happened that you did not expect.

        Provide a clear and concise description of what the problem is and include as many
        details as possible.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: input
    attributes:
      label: Version of Nozzle-Filament-Post-Processor
      description: >-
        The version of the Nozzle-Filament-Post-Processor plugin you are running.
    validations:
      required: true
  - type: input
    attributes:
      label: Operating system running the Post-Processor
      description: >-
        Linux, Windows, MacOS, something else?
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Checklist of files to include below
      options:
        - label: Description of error
        - label: Screenshots and/or videos showing the problem (always include in case of issues with reproduction)
  - type: textarea
    attributes:
      label: Additional information & file uploads